name: Verify ExamplePlugin builds

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Client Release
        run: |
          msbuild "StarRupture-Plugin-SDK.sln" `
            /p:Configuration="Client Release" `
            /p:Platform=x64 `
            /m `
            /v:minimal

      - name: Build Server Release
        run: |
          msbuild "StarRupture-Plugin-SDK.sln" `
            /p:Configuration="Server Release" `
            /p:Platform=x64 `
            /m `
            /v:minimal
